allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bcrypt
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
